/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BucketsIndexRouteImport } from './routes/buckets/index'
import { Route as UploadBucketIdRouteImport } from './routes/upload.$bucketId'
import { Route as BucketsBucketIdRouteImport } from './routes/buckets/$bucketId'
import { ServerRoute as ApiUploadthingServerRouteImport } from './routes/api/uploadthing'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/buckets/',
  path: '/buckets/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadBucketIdRoute = UploadBucketIdRouteImport.update({
  id: '/upload/$bucketId',
  path: '/upload/$bucketId',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsBucketIdRoute = BucketsBucketIdRouteImport.update({
  id: '/buckets/$bucketId',
  path: '/buckets/$bucketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingServerRoute = ApiUploadthingServerRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/upload/$bucketId': typeof UploadBucketIdRoute
  '/buckets': typeof BucketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/upload/$bucketId': typeof UploadBucketIdRoute
  '/buckets': typeof BucketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/buckets/$bucketId': typeof BucketsBucketIdRoute
  '/upload/$bucketId': typeof UploadBucketIdRoute
  '/buckets/': typeof BucketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/buckets/$bucketId'
    | '/upload/$bucketId'
    | '/buckets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/buckets/$bucketId'
    | '/upload/$bucketId'
    | '/buckets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/buckets/$bucketId'
    | '/upload/$bucketId'
    | '/buckets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  BucketsBucketIdRoute: typeof BucketsBucketIdRoute
  UploadBucketIdRoute: typeof UploadBucketIdRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/uploadthing': typeof ApiUploadthingServerRoute
}
export interface FileServerRoutesByTo {
  '/api/uploadthing': typeof ApiUploadthingServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/uploadthing': typeof ApiUploadthingServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/uploadthing'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/uploadthing'
  id: '__root__' | '/api/uploadthing'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUploadthingServerRoute: typeof ApiUploadthingServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$bucketId': {
      id: '/upload/$bucketId'
      path: '/upload/$bucketId'
      fullPath: '/upload/$bucketId'
      preLoaderRoute: typeof UploadBucketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/$bucketId': {
      id: '/buckets/$bucketId'
      path: '/buckets/$bucketId'
      fullPath: '/buckets/$bucketId'
      preLoaderRoute: typeof BucketsBucketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  BucketsBucketIdRoute: BucketsBucketIdRoute,
  UploadBucketIdRoute: UploadBucketIdRoute,
  BucketsIndexRoute: BucketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUploadthingServerRoute: ApiUploadthingServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
